Assorted QoL changes
timower/rM2-stuff pull request #20
Opened 2023-08-04 19:44 UTC by kiwiz

* Fixes physical keyboard repeat
    * This was broken by my previous PR
* Handle screen input rotation
    * Not sure if gestures are handled correctly, but I'm not sure if any gestures are actually in use?
    * I noticed that hovering over the screen with the pen triggers inputs. IMO, only physically tapping the screen should report a mouse input.
* Support for F1 - F12 keys
    * This is currently broken. May need to update the terminfo for this to work properly? Help with this would be appreciated

2023-08-05 21:57 UTC, timower commented on apps/yaft/keyboard.cpp
> +  };
Are you using clang-format?

2023-08-05 22:06 UTC, timower requested changes
Small nits mostly

2023-08-05 22:06 UTC, timower commented on apps/yaft/terminal.cpp
> +  term_resize(term, width, height, isLandscape, false);
```suggestion
  term_resize(term, width, height, isLandscape, /* report */ false);
```

2023-08-05 22:07 UTC, timower commented
> Not sure if gestures are handled correctly, but I'm not sure if any gestures are actually in use?
Two finger scroll should work, but it is kind of flaky.

2023-08-05 22:09 UTC, timower commented
> I noticed that hovering over the screen with the pen triggers inputs. IMO, only physically tapping the screen should report a mouse input.

The idea was to allow mouse moves when hovering. That way you could drag something by touching the screen while moving the pen. Though I don't use the mouse integration that much, so I'm fine with either implementation or a config option.

2023-08-05 22:35 UTC, kiwiz commented on apps/yaft/keyboard.cpp
> +initMouseBuf(terminal_t* term, std::array<char, 6>& buf, Point loc) {
Good catch.

2023-08-05 22:43 UTC, kiwiz commented
> The idea was to allow mouse moves when hovering. That way you could drag something by touching the screen while moving the pen. Though I don't use the mouse integration that much, so I'm fine with either implementation or a config option.

Ah, I see. In that case, I'll see if I can require a physical touch before events start getting fired (if that's not already the case).

2023-08-06 00:31 UTC, kiwiz commented on apps/yaft/keyboard.cpp
> +  };
I am now!

2023-08-07 17:48 UTC, timower commented
> BUG: Keyboard visibility state is broken
Just fixed this, along with pogo detection in [yaft_auto](https://github.com/timower/rM2-stuff/tree/yaft_auto_landscape), I'll get my folio tomorrow to verify if it works.

2023-08-07 18:02 UTC, timower approved these changes
One more nit, but then I'll merge

2023-08-07 18:06 UTC, kiwiz commented
Sweet, hope you enjoy it!

I'll open up a separate PR for the config support (unless if you'd like to take a stab at it) and continue investigating the F# keys.

2023-08-07 18:37 UTC, timower requested changes
This should hopefully fix the F keys

2023-08-07 18:37 UTC, timower commented on apps/yaft/keyboard.cpp
> +
From https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-PC-Style-Function-Keys
```suggestion
  constexpr auto write_ss3 = [](char code) {
    buf[0] = esc_char;
    buf[1] = 'O';
    buf[3] = code;
    buf[4] = 0;
  };

  constexpr auto write_hi_vt_code = [](char a, char b) {
    buf[0] = esc_char;
    buf[1] = '[';
    buf[2] = a;
    buf[3] = b;
    buf[4] = '~';
    buf[5] = 0;
  };

```

2023-08-07 18:37 UTC, timower commented on apps/yaft/keyboard.cpp
> +        return buf.data();
https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-PC-Style-Function-Keys
```suggestion
      case F1:
        write_ss3('p');
        return buf.data();
      case F2:
        write_ss3('Q');
        return buf.data();
      case F3:
        write_ss3('R');
        return buf.data();
      case F4:
        write_ss3('S');
        return buf.data();
```

2023-08-07 18:37 UTC, timower commented on apps/yaft/keyboard.cpp
> +        return buf.data();
```suggestion
      case F5:
        write_hi_vt_code('1', '5');
        return buf.data();
      case F6:
        write_hi_vt_code('1', '7');
        return buf.data();
      case F7:
        write_hi_vt_code('1', '8');
        return buf.data();
      case F8:
        write_hi_vt_code('1', '9');
        return buf.data();
      case F9:
        write_hi_vt_code('2', '0');
        return buf.data();
      case F10:
        write_hi_vt_code('2', '1');
        return buf.data();
      case F11:
        write_hi_vt_code('2', '3');
        return buf.data();
      case F12:
        write_hi_vt_code('2', '4');
        return buf.data();
```

2023-08-07 18:39 UTC, kiwiz commented on apps/yaft/keyboard.cpp
> +        return buf.data();
Testing.

2023-08-07 18:44 UTC, kiwiz commented
> This should hopefully fix the F keys

Looks like F6 - F12 work (in `htop`, at least)

2023-08-07 19:08 UTC, kiwiz commented
With the changes above, F5 - F12 work.

2023-08-07 19:12 UTC, kiwiz commented
Ah, indices were off on the `write_ss3` function. All F# keys work now!

2023-08-08 16:22 UTC, timower approved these changes

2023-08-08 16:22 UTC, merged